# Generated by Django 2.0.6 on 2018-11-11 10:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=255)),
                ('comment_score', models.IntegerField(default=0)),
                ('c_parent_id', models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to='insta.CommentModel')),
            ],
        ),
        migrations.CreateModel(
            name='FollowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_image', models.ImageField(default=None, upload_to='insta/')),
                ('post_caption', models.CharField(blank=True, max_length=200)),
                ('post_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(default='insta/defprofpic.png', upload_to='insta/')),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('score', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.ForeignKey(on_delete='models.CASCADE', to='insta.UserModel'),
        ),
        migrations.AddField(
            model_name='followmodel',
            name='a_username',
            field=models.ForeignKey(on_delete='models.CASCADE', to='insta.UserModel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='c_post_id',
            field=models.ForeignKey(on_delete='models.CASCADE', to='insta.Post'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='c_uid',
            field=models.ForeignKey(on_delete='models.CASCADE', to='insta.UserModel'),
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='post_id',
            field=models.ForeignKey(on_delete='models.CASCADE', to='insta.Post'),
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='uid',
            field=models.ForeignKey(on_delete='models.CASCADE', to='insta.UserModel'),
        ),
    ]
