# Generated by Django 2.0.6 on 2018-11-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_usermodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
